### ISSUE TITLE
build-package.sh erroring with new TravisCI default distro

### ISSUE THREAD

**Issue by mschuchard** [atom/ci#90]
For Travis CI, the default distro of Trusty is currently being phased out in favor of Xenial. When testing a package on Xenial in Travis:

> Running specs...
/home/travis/atom/usr/share/atom/atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
The command "curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh" exited with 127.

When I check for Atom's library links, I hit:

> ldd \`which atom\`
	not a dynamic executable

so I cannot seem to determine myself if this is a link target issue for Atom, or if a dependency needs to be added for TravisCI.

Thanks for any assistance/fix.

**Comment by kkopper** [comment]
I encountered the same problem. As described [here](https://github.com/electron/electron/issues/1518), I just added `libgconf-2-4` to the packages to be installed by apt.
```yaml
addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
    - libgconf-2-4
```

Afterwards, the build script works like a charm.
